# Generated by Django 5.0.3 on 2024-04-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_name', models.CharField(max_length=100)),
                ('Event_Description', models.TextField()),
                ('Event_Venue', models.CharField(max_length=100)),
                ('Event_start_date_time', models.DateTimeField()),
                ('Event_end_date_time', models.DateTimeField()),
                ('Event_Image', models.ImageField(upload_to='')),
            ],
        ),
    ]
